INSERT INTO Games(Name, Description, Category, Price) 
VALUES 
	('SimCity', 'is an open-ended city-building video game series originally designed by Will Wright. The first game in the series, SimCity, was published by Maxis in 1989.', 'Simulator', 20),
	('TITANFALL', 'is a shooter game played from a first-person perspective. Players fight as free-running foot soldier "Pilots" who can command agile, mech-style robots—"Titans"—to complete team-based objectives.', 'Shooter', 25),
	('Battlefield 4', ' is a first-person shooter video game developed by video game developer EA DICE and published by Electronic Arts. It is a sequel to 2011 Battlefield 3 and was released in October 2013 for Microsoft Windows, PlayStation 3, and Xbox 360; then later in November for PlayStation 4 and Xbox One.', 'Shooter', 30),
	('The Sims 4', 'is a life simulation game, similar to its predecessors. Players create a Sim character and control their life to explore different personalities which change the way the game plays out. Sims can now multitask.', 'Simulator', 35),
	('Dark Souls 2', 'is an action role-playing game developed by FromSoftware and published by Bandai Namco Games. The third game in the Souls series, it was released for Microsoft Windows, PlayStation 3 and Xbox 360.', 'RPG', 40),
	('The Elder Scrolls V: Skyrim', 'is an action role-playing game, playable from either a first or third-person perspective. The player may freely roam over the land of Skyrim which is an open world environment consisting of wilderness expanses, dungeons, cities, towns, fortresses, and villages.', 'RPG', 45),
	('FIFA 14', 'Fuelled by EA SPORTS IGNITE, FIFA 14 will feel alive with players who think, move, and behave like world-class footballers, and dynamic stadiums that come to life. Players have four times the decision making ability and feel alive with human-like reactions, anticipation, and instincts.', 'Simulator', 50),
	('Need for Speed Rivals', 'is a racing game and features gameplay similar to earlier Need for Speed titles, such as Criterions Need for Speed: Most Wanted and Need for Speed: Hot Pursuit. Players take on the role of a Racer or Cop, with each side of the law offering its own play style. ', 'Simulator', 55),
	('Crysis 3', 'Similar to the earlier games in the Crysis series, Crysis 3 is a first-person shooter. Players take control of Prophet as he progresses through New York City to defeat the Ceph, a technologically advanced alien race. Throughout the game, players can slide, sprint, jump and crouch.', 'Shooter', 60.00),
	('Dead Space 3', 'is a science fiction survival horror action-adventure video game developed by Visceral Games and published by Electronic Arts. Announced at E3 2012 and released internationally in February 2013, it is the sequel to Dead Space 2 and the third main entry in the Dead Space series.', 'Shooter', 70);